### ISSUE TITLE
将s2项目中的src/errorcode.csv转成json格式, 放到这个项目的aws/errorcode.json的位置.

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/resource#1]
可以通过文本替换转,也可以通过写个小pytnon脚本转. 格式参考mimetype.json,

s2中应用这个errorcode.csv的文件在`s2offline.py` 有例子.

**Comment by drmingdrmer** [comment]
唔...刚看 `baishancloud/pykit/aws`已经有error定义了. 那就把那个整理好的yaml转移到resource里再通过git-subrepo合并回pykit. 数据用json吧.

**Comment by drmingdrmer** [comment]
这个可以关了吧? @lishulong

**Comment by lishulong** [comment]
可以关了。
